using System;
using System.Numerics;
using CerberusWareV3.Interface.Controls;
using CerberusWareV3.Localization;
using Robust.Client.AutoGenerated;
using Robust.Shared.Player;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Player;

namespace CerberusWareV3.Interface;

[GenerateTypedNameReferences]
public sealed partial class PlayerInfoWindow : DefaultWindow
{
    [Dependency] private readonly IEntitySystemManager _sysMan = default!;
    
    private PlayerData? _playerData;
    private EntityPreviewSystem? _entityPreview;

    public PlayerInfoWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        
        _entityPreview = _sysMan.GetEntitySystem<EntityPreviewSystem>();
    }

    public void SetPlayerData(PlayerData playerData)
    {
        _playerData = playerData;
        UpdateContent();
    }

    private void UpdateContent()
    {
        BoxContainer? contentContainer;
        try
        {
            contentContainer = FindControl<BoxContainer>("ContentContainer");
        }
        catch
        {
            return;
        }
        contentContainer.RemoveAllChildren();

        if (_playerData == null)
            return;

        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(10)
        };

        // Player name
        var nameLabel = new Label
        {
            Text = $"Name: {_playerData.Session.Name}",
            FontColorOverride = Color.White,
            Margin = new Thickness(0, 0, 0, 10)
        };
        container.AddChild(nameLabel);

        // Character name
        var charLabel = new Label
        {
            Text = $"Character: {_playerData.EntityName}",
            FontColorOverride = Color.White,
            Margin = new Thickness(0, 0, 0, 10)
        };
        container.AddChild(charLabel);

        // Entity UID
        var entityLabel = new Label
        {
            Text = $"Entity: {_playerData.AttachedEntity?.ToString() ?? "None"}",
            FontColorOverride = Color.White,
            Margin = new Thickness(0, 0, 0, 10)
        };
        container.AddChild(entityLabel);

        // Status
        var statusLabel = new Label
        {
            Text = $"Status: {_playerData.Status}",
            FontColorOverride = _playerData.Status == "Online" ? Color.Green : Color.Red,
            Margin = new Thickness(0, 0, 0, 10)
        };
        container.AddChild(statusLabel);

        // Job
        var jobLabel = new Label
        {
            Text = $"Job: {_playerData.Job}",
            FontColorOverride = Color.White,
            Margin = new Thickness(0, 0, 0, 10)
        };
        container.AddChild(jobLabel);

        // Position
        var posLabel = new Label
        {
            Text = $"Position: {_playerData.LastKnownPosition.X:F2}, {_playerData.LastKnownPosition.Y:F2}",
            FontColorOverride = Color.White,
            Margin = new Thickness(0, 0, 0, 10)
        };
        container.AddChild(posLabel);

        // Entity preview
        if (_playerData.AttachedEntity.HasValue)
        {
            var previewContainer = new PanelContainer
            {
                MinHeight = 200,
                MinWidth = 200,
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 10, 0, 10)
            };
            previewContainer.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = new Color(23, 24, 28),
                BorderThickness = new Thickness(1),
                BorderColor = new Color(50, 50, 50)
            };

            var previewLabel = new Label
            {
                Text = "Entity Preview",
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                FontColorOverride = Color.Gray
            };
            previewContainer.AddChild(previewLabel);

            // Render preview asynchronously
            if (_entityPreview != null)
            {
                _entityPreview.RenderSpriteAsync(_playerData.AttachedEntity.Value, 0, default);
            }

            container.AddChild(previewContainer);
        }

        contentContainer.AddChild(container);
    }
}

