using System;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;

namespace CerberusWareV3.Interface;

[GenerateTypedNameReferences]
public sealed partial class SettingsPopupWindow : DefaultWindow
{
    public string UniqueId { get; set; } = "";
    public Action<string>? RenderContent;

    public SettingsPopupWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateContent()
    {
        try
        {
            var contentContainer = FindControl<BoxContainer>("ContentContainer");
            contentContainer.RemoveAllChildren();
            RenderContent?.Invoke(UniqueId);
        }
        catch
        {
            // ContentContainer will be generated by XAML
        }
    }
}

